### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by WhyNotHugo** [jvaelen/2048#2]
Build instructions seem to be missing: There's no Makefile CMakefile, or anything similar which makes this obvious.

**Comment by jvaelen** [comment]
@hobarrera 
The idea is to build the project in the Qt SDK using the .pro file.

**Comment by WhyNotHugo** [comment]
Thanks for you're feedback, back. I noticed you've closed the issue, but I don't see any related commits. Are you sure you meant to close it?

Also on topic: Qt SDK? All references I've found to it point to now-dead URLs at nokia's site ([example](http://doc.qt.digia.com/sdk-1.1/sdk-installing.html)).

**Comment by WhyNotHugo** [comment]
Mind you: my intention is not for you to guide my step-by-step on how to install this myself, but rather to include the basic required information on `README.md` so that anyone can find this out themselves.

**Comment by jvaelen** [comment]
@hobarrera I'll add more detailed instruction on how to build the project using Qt. Reopened.

**Comment by jvaelen** [comment]
Added build instructions to `README`

**Comment by WhyNotHugo** [comment]
Thanks!

However, regrettably, my intention is to package this downstream for ArchLinux. These build instructions cannot be scripted (and can't be used by packagers of any distribution either).

I used the above as a reference, and found that `qmake && make` will also build the project successfully (most distributions will include this `qmake` and `make` out-of-the-box too).

**Comment by jvaelen** [comment]
Hah okay, interesting. Now build instructions make more sense. I never tried building outside Qt Creator. I'll add your findings too though.

**Comment by WhyNotHugo** [comment]
Thanks! :)
