### ISSUE TITLE
bug: sometimes performed more additions than it should

### ISSUE THREAD

**Issue by schdub** [jvaelen/2048#4]
Hi.

For example, we've a column of numbers:

2
4
2
2

аfter pressing 'down', it should turn out:

*
2
4
4

but we get:

*
*
2
8

see screenshots:
![screenshot from 2015-05-15 01 14 21](https://cloud.githubusercontent.com/assets/1304776/7643705/78ba4fe8-faa4-11e4-90d6-c12fa2c06fa5.png)
![screenshot from 2015-05-15 01 14 38](https://cloud.githubusercontent.com/assets/1304776/7643735/9ff97552-faa4-11e4-8cc3-7fa5f85f5f68.png)

For example, the correct behaviour in the last row by pressing 'left'
![screenshot from 2015-05-15 01 34 44](https://cloud.githubusercontent.com/assets/1304776/7643746/c634fa20-faa4-11e4-8894-dd09c5e4154a.png)
![screenshot from 2015-05-15 01 35 02](https://cloud.githubusercontent.com/assets/1304776/7643752/d58d11d8-faa4-11e4-9e3d-87b38913e882.png)

It's correct behaviour?

**Comment by jvaelen** [comment]
Interesting, I'll have a look, thanks for reporting!

**Comment by wzc971028ha** [comment]
11
